# Generated by Django 4.1 on 2022-08-31 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('std_ID', models.CharField(default='16201519-001', max_length=12, primary_key=True, serialize=False)),
                ('std_name', models.CharField(default='', max_length=50)),
                ('std_gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other')], default='M', max_length=1)),
                ('std_class', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
